jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.143.0'
          extended: true

      - name: Setup Hugo Modules
        run: hugo mod tidy

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --minify

      - name: Debug: List repository root
        run: ls -la

      - name: Debug: List public folder
        run: ls -laR public || echo "public folder not found"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

